// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdzjQmfBkMTr5cRi1yBUFJaO_vXdC75U',
    appId: '1:579705651158:web:053028c32a715e4f38ae77',
    messagingSenderId: '579705651158',
    projectId: 'telegram-app-37d98',
    authDomain: 'telegram-app-37d98.firebaseapp.com',
    storageBucket: 'telegram-app-37d98.appspot.com',
    measurementId: 'G-KD1S5R7N6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFQMBJ_KlxGHf06vlgFwukr7vGiEnC9w',
    appId: '1:579705651158:android:702d01febce5875d38ae77',
    messagingSenderId: '579705651158',
    projectId: 'telegram-app-37d98',
    storageBucket: 'telegram-app-37d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPRvwIWVxIyDl9quovVYvaCBUINSfilN8',
    appId: '1:579705651158:ios:d9dd49618156589138ae77',
    messagingSenderId: '579705651158',
    projectId: 'telegram-app-37d98',
    storageBucket: 'telegram-app-37d98.appspot.com',
    iosClientId: '579705651158-r1sd6i707qgbv3dqq0fp8cu5t4mmnpna.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPRvwIWVxIyDl9quovVYvaCBUINSfilN8',
    appId: '1:579705651158:ios:d9dd49618156589138ae77',
    messagingSenderId: '579705651158',
    projectId: 'telegram-app-37d98',
    storageBucket: 'telegram-app-37d98.appspot.com',
    iosClientId: '579705651158-r1sd6i707qgbv3dqq0fp8cu5t4mmnpna.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramApp',
  );
}
