// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUlg_E_unvm60-IVGwvpbRqmv4d7jeVM',
    appId: '1:752407456034:web:2bbfa68ea2130fd3205d7b',
    messagingSenderId: '752407456034',
    projectId: 'telegram-app-3f52e',
    authDomain: 'telegram-app-3f52e.firebaseapp.com',
    storageBucket: 'telegram-app-3f52e.appspot.com',
    measurementId: 'G-MWN5NCBBR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVXMihePzflW20ExvxPdMInkhN7aCliI',
    appId: '1:752407456034:android:248455625dfe2683205d7b',
    messagingSenderId: '752407456034',
    projectId: 'telegram-app-3f52e',
    storageBucket: 'telegram-app-3f52e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-jBbDDaBeEQ4inmm9rSE18WTcJC108Q',
    appId: '1:752407456034:ios:c52f2e22c3388b04205d7b',
    messagingSenderId: '752407456034',
    projectId: 'telegram-app-3f52e',
    storageBucket: 'telegram-app-3f52e.appspot.com',
    iosClientId:
        '752407456034-7h434ork93aibiaak5k5nh1h7pee9nep.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-jBbDDaBeEQ4inmm9rSE18WTcJC108Q',
    appId: '1:752407456034:ios:c52f2e22c3388b04205d7b',
    messagingSenderId: '752407456034',
    projectId: 'telegram-app-3f52e',
    storageBucket: 'telegram-app-3f52e.appspot.com',
    iosClientId:
        '752407456034-7h434ork93aibiaak5k5nh1h7pee9nep.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramApp',
  );
}
